from torchtext.data.metrics import bleu_score

def calculate_bleu(references, candidates):
    """
    Calculate BLEU score for image captions.
    
    Args:
        references (list of list of str): list of reference captions (tokenized) for each image.
        candidates (list of str): list of candidate captions (tokenized) generated by model.
    Returns:
        float: BLEU score
    """
    if all(isinstance(ref, str) for ref in references):
        references = [references]

    if isinstance(candidates, str):
        candidates = [candidates.split()]

    return bleu_score(candidates, references)